Fix random_string resource numeric input deprecation
DNXLabs/terraform-aws-securityhub pull request #9
Opened 2022-10-08 13:42 UTC by arthurbdiniz

Signed-off-by: Arthur Diniz <arthurbdiniz@gmail.com>

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

This module uses a resource called `random_string`. This resource has an input field that is deprecated and it's a good idea to update to the new format.

**number -> numeric**

No breaking changes.

## Types of changes

What types of changes does your code introduce to <repo_name>?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the CONTRIBUTING.md doc.
- [x] I have added the necessary documentation (if appropriate).
- [x] Any dependent changes have been merged and published in downstream modules.

## Further comments

Before:
```
╷
│ Warning: Attribute Deprecated
│ 
│   with module.securityhub.random_string.to_slack_cf_suffix,
│   on .terraform/modules/securityhub/event-to-slack-cf.tf line 7, in resource "random_string" "to_slack_cf_suffix":
│    7:   number  = false
│ 
│ **NOTE**: This is deprecated, use `numeric` instead.
```

After:

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.securityhub.aws_securityhub_account.default will be created
  + resource "aws_securityhub_account" "default" {
      + id = (known after apply)
    }

  # module.securityhub.aws_securityhub_standards_subscription.cis[0] will be created
  + resource "aws_securityhub_standards_subscription" "cis" {
      + id            = (known after apply)
      + standards_arn = "arn:aws:securityhub:::ruleset/cis-aws-foundations-benchmark/v/1.2.0"
    }

  # module.securityhub.aws_securityhub_standards_subscription.foundational[0] will be created
  + resource "aws_securityhub_standards_subscription" "foundational" {
      + id            = (known after apply)
      + standards_arn = "arn:aws:securityhub:sa-east-1::standards/aws-foundational-security-best-practices/v/1.0.0"
    }

Plan: 3 to add, 0 to change, 0 to destroy.
```

2022-10-08 13:49 UTC, caiovfernandes approved these changes

2022-10-09 01:45 UTC, lzrocha submitted a review, later dismissed

2022-10-10 22:07 UTC, brunodasilvalenga requested changes
Hey @arthurbdiniz  could you consider including the minimum AWS provider version that supports the new feature?

2022-10-11 01:03 UTC, arthurbdiniz commented
> Hey @arthurbdiniz could you consider including the minimum AWS provider version that supports the new feature?

Hey @brunodasilvalenga, this was a change on the `random` provider and not `AWS` terraform provider.  As a warning deprecation, the old attribute will only be removed on the next `MAJOR` release of the provider following [Provider Attribute Rename Docs](https://www.terraform.io/plugin/sdkv2/best-practices/deprecations#provider-attribute-rename).

- [Attribute Change Pull Request](https://github.com/hashicorp/terraform-provider-random/pull/258)
- [terraform-provider-random release v3.3.0](https://github.com/hashicorp/terraform-provider-random/releases/tag/v3.3.0)

So in my opinion the best approach is to define the version to `>= v3.3.0`. 

```
required_providers {
    random = ">= 3.3.0"
}
```

If you have other approaches for this requirement I will be around to discuss and make the necessary changes.

2022-10-11 05:38 UTC, brunodasilvalenga approved these changes

2022-10-11 05:38 UTC, merged